AUTH0_DOMAIN = os.environ.get('AUTH0_DOMAIN')
ALGORITHMS = os.environ.get('ALGORITHMS')
API_AUDIENCE = os.environ.get('API_AUDIENCE')
URL = os.environ.get('URL')
Redirect_URI = os.environ.get('Redirect_URI')
SQL_DATABASE_URI = os.environ.get('SQL_DATABASE_URI')