"""empty message

Revision ID: 32770e7ac863
Revises: None
Create Date: 2021-09-10 00:40:52.476779

"""

# revision identifiers, used by Alembic.
revision = '32770e7ac863'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drink')
    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('permissions_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='role_pkey'),
    sa.UniqueConstraint('name', name='role_name_key')
    )
    op.create_table('drink',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('recipe', sa.VARCHAR(length=180), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='drink_pkey'),
    sa.UniqueConstraint('title', name='drink_title_key')
    )
    # ### end Alembic commands ###
